exports.BusinessStep = function(callback){
	var businessStep		=	[
									{value:'BusinessStepEnter',			text:'Manually'},
									{value:'accepting', 				text:'Accepting'},
									{value:'arriving', 					text:'Arriving'},
									{value:'collecting', 				text:'Collecting'},
									{value:'commissioning', 			text:'Commissioning'},
									{value:'consigning', 				text:'Consigning'},
									{value:'creating_class_instance', 	text:'Creating Class Instance'},
									{value:'cycle_counting', 			text:'Cycle Counting'},
									{value:'decommissioning', 			text:'Decommissioning'},
									{value:'departing', 				text:'Departing'},
									{value:'destroying', 				text:'Destroying'},
									{value:'dispensing', 				text:'Dispensing'},
									{value:'entering_exiting', 			text:'Entering Exiting'},
									{value:'entering_exit', 			text:'Entering Exit'},
									{value:'inspecting', 				text:'Inspecting'},
									{value:'installing', 				text:'Installing'},
									{value:'loading', 					text:'Loading'},
									{value:'picking', 					text:'Picking'},
									{value:'receiving', 				text:'Receiving'},
									{value:'removing', 					text:'Removing'},
									{value:'repackaging', 				text:'Repackaging'},
									{value:'repairing', 				text:'Repairing'},
									{value:'replacing', 				text:'Replacing'},
									{value:'retail_selling', 			text:'Retail Selling'},
									{value:'shipping', 					text:'Shipping'}
								];
		
	var dispositions 		= 	[
									{value:'DispositionEnter',			text: 'Enter Disposition Manually'},
									{value:'active',					text: 'Active'},
									{value:'container_closed',			text: 'Container Closed'},
									{value:'damaged',					text: 'Damaged'},
									{value:'destroyed',					text: 'Destroyed'},
									{value:'dispensed',					text: 'Dispensed'},
									{value:'disposed',					text: 'Disposed'},
									{value:'encoded',					text: 'Encoded'},
									{value:'expired',					text: 'Expired'},
									{value:'in_progress',				text: 'In Progress'},
									{value:'in_transit',				text: 'In Transit'},
									{value:'inactive',					text: 'Inactive'},
									{value:'no_pedigree_match',			text: 'No Pedigree Match'},
									{value:'non_sellable_other',		text: 'Non Sellable Other'},
									{value:'partially_dispensed',		text: 'Partially Dispensed'},
									{value:'recalled',					text: 'Recalled'}
								];
		
	var eventType 			= 	[
									{value:'ObjectEvent', 				text:'Object Event'},
									{value:'AggregationEvent', 			text:'Aggregation Event'},
									{value:'TransactionEvent', 			text:'Transaction Event'},
									{value:'TransformationEvent', 		text:'Transformation Event'},
									{value:'AssociationEvent',			text:'Association Event'}
								];
								
	var companyPrefixs		=	[
									{value:'6', 						text:'6 Digits'},
									{value:'7', 						text:'7 Digits'},
									{value:'8', 						text:'8 Digits'},
									{value:'9', 						text:'9 Digits'},
									{value:'10', 						text:'10 Digits'},
									{value:'11', 						text:'11 Digits'},
									{value:'12', 						text:'12 Digits'},
								];
	
	var ObjectEventEpcsTypes=	[
									{value:'GS1 Key',					text:'GS1 Key', 				class:'bold',	disabled:true},
									{value:'SGTIN (Al 01 + Al 21)',		text:'SGTIN (Al 01 + Al 21)'},
									{value:'SSCC (Al 00)',				text:'SSCC (Al 00)'},
									{value:'GRAI (Al 8003)',			text:'GRAI (Al 8003)'},
									{value:'GIAI (Al 8004)',			text:'GIAI (Al 8004)'},
									{value:'GSRN (Al 8018)',			text:'GSRN (Al 8018)'},
									{value:'GSRNP (Al 8017)',			text:'GSRNP (Al 8017)'},
									{value:'GDTI (Al 253)',				text:'GDTI (Al 253)'},
									{value:'GCN (Al 255)',				text:'GCN (Al 255)'},
									{value:'CPI (Al 8010 8011)',		text:'CPI (Al 8010 + Al 8011)'},
									{value:'GINC (Al 401)',				text:'GINC (Al 401)'},
									{value:'GSIN (Al 402)',				text:'GSIN (Al 402)'},
									{value:'ITIP (Al 8006 + Al 21)',	text:'ITIP (Al 8006 + Al 21)'},
									{value:'UPI_UI (Al 01 + Al 235)',	text:'UPIUI (Al 01 + Al 235)'},
									{value:'Other EPC Identifier',		text:'Other EPC Identifier',	class:'bold',	disabled:true},
									{value:'GID',						text:'GID'},
									{value:'USDoD',						text:'USDoD'},
									{value:'ADI',						text:'ADI'},
									{value:'BIC',						text:'BIC'},
									{value:'IMOVN',						text:'IMOVN'},
									{value:'Other',						text:'Other',					class:'bold',	disabled:true},
									{value:'Enter a URI Manually',		text:'Enter a URI Manually'}
								];
	
	var ObjectEventQuantities=	[
									{value:'GS1 Key',					text:'GS1 Key', 				class:'bold',	disabled:true},
									{value:'LGTIN (Al 01 + Al 10)', 	text:'LGTIN (Al 01 + Al 10)'},
									{value:'GTIN, no serial (Al 01)', 	text:'GTIN, no serial (Al 01)'},
									{value:'GRAI, no serial (Al 8003)',	text:'GRAI, no serial (Al 8003)'},
									{value:'GDTI, no serial (Al 253)', 	text:'GDTI, no serial (Al 253)'},
									{value:'GCN, no serial (Al 255)', 	text:'GCN, no serial (Al 255)'},
									{value:'CPI, no serial (Al 801 0)',	text:'CPI, no serial (Al 801 0)'},
									{value:'ITIP, no serial (Al 8006)',	text:'ITIP, no serial (Al 8006)'},
									{value:'UPUI, no TPX (Al 01)', 		text:'UPUI, no TPX (Al 01)'},
									{value:'Other',						text:'Other',					class:'bold',	disabled:true},
									{value:'Enter a URI Manually',		text:'Enter a URI Manually'}
								];
	
	var UOMs					=	[
									{value:'Mass',					text:'Mass', 				class:'bold',	disabled:true},
									{value:"KGM",					text:"Kilogram"},
									{value:"KTN",					text:"Kilotonne"},
									{value:"LTN",					text:"Ton (UK) or long ton (US)"},
									{value:"2U",					text:"Megagram"},
									{value:"TNE",					text:"Tonne (metric ton)"},
									{value:"STN",					text:"Ton (US) or short ton (UK/US)"},
									{value:"DTN",					text:"Decitonne"},
									{value:"STI",					text:"Stone (UK)"},
									{value:"LBR",					text:"Pound"},
									{value:"HGM",					text:"Hectogram"},
									{value:"ONZ",					text:"Ounce"},
									{value:"DJ",					text:"Decagram"},
									{value:"APZ",					text:"Troy ounce or apothecary ounce"},
									{value:"GRM",					text:"Gram"},
									{value:"DG",					text:"Decigram"},
									{value:"CGM",					text:"Centigram"},
									{value:"MGM",					text:"Milligram"},
									{value:"MC",					text:"Microgram"},
									{value:"F13",					text:"Slug"},
									{value:"CWI",					text:"Hundred weight (UK)"},
									{value:"CWA",					text:"Hundred pound (cwt) / hundred weight (US)"},
									{value:"M86",					text:"Pfund"},
									{value:"58",					text:"Net kilogram"},
									{value:"DRA",					text:"Dram (US)"},
									{value:"DRI",					text:"Dram (UK)"},
									{value:"E4",					text:"Gross kilogram"},
									{value:"GRN",					text:"Grain"},
									{value:"PN",					text:"Pound net"},
									{value:"DWT",					text:"Pennyweight"},
									{value:'Length',				text:'Length', 				class:'bold',	disabled:true},
									{value:"MTR",					text:"Metre"},
									{value:"A11",					text:"Angstrom"},
									{value:"A71",					text:"Femtometre"},
									{value:"C45",					text:"Nanometre"},
									{value:"4H",					text:"Micrometre"},
									{value:"A12",					text:"Astronomical unit"},
									{value:"DMT",					text:"Decimetre"},
									{value:"CMT",					text:"Centimetre"},
									{value:"MMT",					text:"Millimetre"},
									{value:"INH",					text:"Inch"},
									{value:"FOT",					text:"Foot"},
									{value:"YRD",					text:"Yard"},
									{value:"NMI",					text:"Nautical mile"},
									{value:"A45",					text:"Decametre"},
									{value:"HMT",					text:"Hectometre"},
									{value:"KMT",					text:"Kilometre"},
									{value:"B57",					text:"Light year"},
									{value:"AK",					text:"Fathom"},
									{value:"M50",					text:"Furlong"},
									{value:"M49",					text:"Chain (based on US survey foot)"},
									{value:"X1",					text:"Gunter's chain"},
									{value:"M51",					text:"Foot (US survey)"},
									{value:"HL",					text:"Hundred foot (linear)"},
									{value:"LF",					text:"Linear foot"},
									{value:"LK",					text:"Link"},
									{value:"LM",					text:"Linear metre"},
									{value:"SMI",					text:"Mile (statute mile)"},
									
								];
	
	
	var SensorElements		=	[
									{value:'User_Defined_Sensor',	text:'User_Defined_Sensor'},
									{value:'Temperature',			text:'Temperature'},
									{value:'Pressure',				text:'Pressure'},
									{value:'Humidity',				text:'Humidity'},
									{value:'Speed',					text:'Speed'},
									{value:'Illuminance',			text:'Illuminance'},
									{value:'molar_concentration',	text:'Molar Concentration'},
								];
	
	var SensorValueTypes	=	[
									{value:'Discrete',				text:'Discrete'},
									{value:'Range',					text:'Range'},
									{value:'Boolean',				text:'Boolean'},
									{value:'User_Defined',			text:'User Defined'}
								];
								
	var SensorUOMs		=	[
									{value:'Temperature UOM',		text:'Temperature UOM', 		class:'bold',	disabled:true, UOMtype:'Temperature'},
									{value:'KEL',					text:'Kelvin',								UOMtype:'Temperature'},
									{value:'FAH',					text:'Fahrenheit',							UOMtype:'Temperature'},
									{value:'CEL',					text:'Celsius',								UOMtype:'Temperature'},
									{value:'A48',					text:'Rankine',								UOMtype:'Temperature'},
									{value:'Humidity	UOM',		text:'Humidity UOM', 			class:'bold',	disabled:true, UOMtype:'Humidity'},
									{value:"KMQ",					text:"Kilogram per cubic metre",			UOMtype:'Humidity'},
									{value:"23",					text:"Gram per cubic centimetre",			UOMtype:'Humidity'},
									{value:"D41",					text:"Tonne per cubic metre",				UOMtype:'Humidity'},
									{value:"GJ",					text:"Gram per millilitre",					UOMtype:'Humidity'},
									{value:"B35",					text:"Kilogram per litre",					UOMtype:'Humidity'},
									{value:"GL",					text:"Gram per litre",						UOMtype:'Humidity'},
									{value:"A93",					text:"Gram per cubic metre",				UOMtype:'Humidity'},
									{value:"GP",					text:"Milligram per cubic metre",			UOMtype:'Humidity'},
									{value:"B72",					text:"Megagram per cubic metre",			UOMtype:'Humidity'},
									{value:"B34",					text:"Kilogram per cubic decimetre",		UOMtype:'Humidity'},
									{value:"H29",					text:"Microgram per litre",					UOMtype:'Humidity'},
									{value:"M1",					text:"Milligram per litre",					UOMtype:'Humidity'},
									{value:"GQ",					text:"Microgram per cubic metre",			UOMtype:'Humidity'},
									{value:"F23",					text:"Gram per cubic decimetre",			UOMtype:'Humidity'},
									{value:"G31",					text:"Kilogram per cubic centimetre",		UOMtype:'Humidity'},
									{value:"87",					text:"Pound per cubic foot",				UOMtype:'Humidity'},
									{value:"GE",					text:"Pound per gallon (US)",				UOMtype:'Humidity'},
									{value:"LA",					text:"Pound per cubic inch",				UOMtype:'Humidity'},
									{value:"G32",					text:"Ounce per cubic yard",				UOMtype:'Humidity'},
									{value:"K41",					text:"Grain per gallon (US)",				UOMtype:'Humidity'},
									{value:"K71",					text:"Pound per gallon (UK)",				UOMtype:'Humidity'},
									{value:"K84",					text:"Pound per cubic yard",				UOMtype:'Humidity'},
									{value:"L37",					text:"Ounce per gallon (UK)",				UOMtype:'Humidity'},
									{value:"L38",					text:"Ounce per gallon (US)",				UOMtype:'Humidity'},
									{value:"L39",					text:"Ounce per cubic inch",				UOMtype:'Humidity'},
									{value:"L65",					text:"Slug per cubic foot",					UOMtype:'Humidity'},
									{value:"L92",					text:"Ton (UK long) per cubic yard",		UOMtype:'Humidity'},
									{value:"L93",					text:"Ton (US short) per cubic yard",		UOMtype:'Humidity'},
									{value:'Speed	UOM',			text:'Speed UOM', 				class:'bold',	disabled:true, UOMtype:'Speed'},
									{value:"KMH",					text:"Kilometres per hour",					UOMtype:'Speed'},
									{value:"MTS",					text:"Metres per second",					UOMtype:'Speed'},
									{value:"HM",					text:"Miles per hour",						UOMtype:'Speed'},
									{value:"M57",					text:"Miles per minute",					UOMtype:'Speed'},
									{value:"M58",					text:"Miles per second",					UOMtype:'Speed'},
									{value:"KNT",					text:"Knot",								UOMtype:'Speed'},
									{value:"M62",					text:"Kilometres per second",				UOMtype:'Speed'},
									{value:"H49",					text:"Centimetres per hour'd",				UOMtype:'Speed'},
									{value:"2M",					text:"Centimetres per second",				UOMtype:'Speed'},
									{value:"K14",					text:"Foot per hour",						UOMtype:'Speed'},
									{value:"FR",					text:"Foot per minute",						UOMtype:'Speed'},
									{value:"FS",					text:"Foot per second",						UOMtype:'Speed'},
									{value:"M63",					text:"Inch per minute",						UOMtype:'Speed'},
									{value:"IU",					text:"Inch per second",						UOMtype:'Speed'},
									{value:"M61",					text:"Inch per year",						UOMtype:'Speed'},
									{value:"2X",					text:"Metre per minute",					UOMtype:'Speed'},
									{value:'Illuminance	UOM',		text:'Illuminance UOM', 				class:'bold',	disabled:true, UOMtype:'Illuminance'},
									{value:"B60",					text:"lumen per square metre",				UOMtype:'Illuminance'},
									{value:"LUX",					text:"lux",									UOMtype:'Illuminance'},
									{value:"KLX",					text:"kilolux",								UOMtype:'Illuminance'},
									{value:"P25",					text:"lumen per square foot",				UOMtype:'Illuminance'},
									{value:"P26",					text:"phot",								UOMtype:'Illuminance'},
									{value:"P27",					text:"footcandle",							UOMtype:'Illuminance'},
									{value:'Pressure	UOM',		text:'Pressure UOM', 					class:'bold',	disabled:true, UOMtype:'Pressure'},
									{value:"PAL",					text:"Pascal",								UOMtype:'Pressure'},
									{value:"H75",					text:"Decapascal",							UOMtype:'Pressure'},
									{value:"74",					text:"Millipascal",							UOMtype:'Pressure'},
									{value:"A89",					text:"Gigapascal",							UOMtype:'Pressure'},
									{value:"A97",					text:"Hectopascal",							UOMtype:'Pressure'},
									{value:"B96",					text:"Micropascal",							UOMtype:'Pressure'},
									{value:"KPA",					text:"Kilopascal",							UOMtype:'Pressure'},
									{value:"MPA",					text:"Megapascal",							UOMtype:'Pressure'},			
									{value:"BAR",					text:"Bar",									UOMtype:'Pressure'},
									{value:"MBR",					text:"Millibar","symbol":"mbar",			UOMtype:'Pressure'},
									{value:"C55",					text:"Newton per square metre",				UOMtype:'Pressure'},
									{value:"C56",					text:"Newton per square millimetre",		UOMtype:'Pressure'},
									{value:"B40",					text:"Kilogram-force per square metre",		UOMtype:'Pressure'},
									{value:"UA",					text:"Torr",								UOMtype:'Pressure'},
									{value:"80",					text:"Pound per square inch absolute",		UOMtype:'Pressure'},
									{value:"H78",					text:"Conventional centimetre of water",	UOMtype:'Pressure'},
									{value:"HP",					text:"Conventional millimetre of water",	UOMtype:'Pressure'},
									{value:"F79",					text:"Inch of mercury",						UOMtype:'Pressure'},
									{value:"F78",					text:"Inch of water",						UOMtype:'Pressure'},
									{value:"ATT",					text:"Technical atmosphere",				UOMtype:'Pressure'},			
									{value:"ATM",					text:"Standard atmosphere",					UOMtype:'Pressure'},
									{value:"J89",					text:"Centimetres of mercury",				UOMtype:'Pressure'},
									{value:"K24",					text:"Foot of water",						UOMtype:'Pressure'},
									{value:"K25",					text:"Foot of mercury",						UOMtype:'Pressure'},
									{value:"K31",					text:"Gram-force per square centimetre",	UOMtype:'Pressure'},
									{value:"E42",					text:"Kilogram-force per square centimetre",UOMtype:'Pressure'},
									{value:"E41",					text:"Kilogram-force per square millimetre",UOMtype:'Pressure'},
									{value:"K85",					text:"Pound-force per square foot",			UOMtype:'Pressure'},
									{value:"84",					text:"Kilopounds force per square inch",	UOMtype:'Pressure'},
									{value:"N13",					text:"Centimetre of mercury (0 ºC)",		UOMtype:'Pressure'},
									{value:"N14",					text:"Centimetre of water (4 ºC)",			UOMtype:'Pressure'},
									{value:"N15",					text:"Foot of water (39.2 ºF)",				UOMtype:'Pressure'},
									{value:"N16",					text:"Inch of mercury (32 ºF)",				UOMtype:'Pressure'},
									{value:"N17",					text:"Inch of mercury (60 ºF)",				UOMtype:'Pressure'},
									{value:"N18",					text:"Inch of water (39.2 ºF)",				UOMtype:'Pressure'},
									{value:"N19",					text:"Inch of water (60 ºF)",				UOMtype:'Pressure'},
									{value:"N20",					text:"Kip per square inch",					UOMtype:'Pressure'},
									{value:"N21",					text:"Poundal per square foot",				UOMtype:'Pressure'},
									{value:"N22",					text:"Ounce (avoirdupois) per square inch",	UOMtype:'Pressure'},
									{value:"N23",					text:"Conventional metre of water",			UOMtype:'Pressure'},
									{value:"HN",					text:"Millimetres of mercury",				UOMtype:'Pressure'},
									{value:"PS",					text:"Pound force per square inch",			UOMtype:'Pressure'}
								];
							

	var returnData = {
						'businessStep'			: 	businessStep, 
						'eventType'				:	eventType, 
						'dispositions'			:	dispositions, 
						'companyPrefixs'		:	companyPrefixs, 
						'ObjectEventEpcsTypes'	:	ObjectEventEpcsTypes,
						'ObjectEventQuantities'	:	ObjectEventQuantities,
						'UOMs'					:	UOMs,
						'SensorElements'		:	SensorElements,
						'SensorUOMs'			:	SensorUOMs,
						'SensorValueTypes'		:	SensorValueTypes
					};
	
	callback(returnData);
}